/*
 * generated by Xtext 2.25.0
 */
package tools.refinery.language.validation;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ProblemValidator extends AbstractProblemValidator {
}
