enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      search-insights: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docusaurus/babel@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/bundler@*":
    peerDependencies:
      "@swc/core": "*"
      lightningcss: "*"
      react: "*"
      react-dom: "*"
      typescript: "*"
  "@docusaurus/core@*":
    peerDependencies:
      "@swc/core": "*"
      lightningcss: "*"
      typescript: "*"
  "@docusaurus/faster@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-client-redirects@*":
    peerDependencies:
      "@docusaurus/faster": "*"
      "@mdx-js/react": "*"
      "@swc/core": "*"
      lightningcss: "*"
      typescript: "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@docusaurus/faster": "*"
      "@mdx-js/react": "*"
      "@swc/core": "*"
      lightningcss: "*"
      typescript: "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@docusaurus/faster": "*"
      "@mdx-js/react": "*"
      "@swc/core": "*"
      lightningcss: "*"
      typescript: "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@docusaurus/faster": "*"
      "@mdx-js/react": "*"
      "@swc/core": "*"
      lightningcss: "*"
      typescript: "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@docusaurus/faster": "*"
      "@mdx-js/react": "*"
      "@swc/core": "*"
      lightningcss: "*"
      typescript: "*"
  "@docusaurus/theme-classic@*":
    peerDependencies:
      "@docusaurus/faster": "*"
      "@swc/core": "*"
      lightningcss: "*"
      typescript: "*"
  "@docusaurus/theme-common@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@algolia/client-search": "*"
      "@docusaurus/faster": "*"
      "@mdx-js/react": "*"
      "@swc/core": "*"
      lightningcss: "*"
      search-insights: "*"
      typescript: "*"
  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@mui/x-data-grid@*":
    peerDependencies:
      "@types/react": "*"
  "@mui/x-internals@*":
    peerDependencies:
      react-dom: "*"
  "@vitest/browser-playwright@*":
    peerDependencies:
      "@testing-library/dom": "*"
      "@testing-library/user-event": "*"
      "@vitest/runner": "*"
      vite: "*"
  "@vitest/browser@*":
    peerDependencies:
      "@testing-library/dom": "*"
      "@testing-library/user-event": "*"
      "@vitest/runner": "*"
      vite: "*"
  notistack@*:
    peerDependencies:
      csstype: "*"
  vite-plugin-dts@*:
    peerDependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
