#!/bin/sh
# SPDX-FileCopyrightText: 2024 The Refinery Authors <https://refinery.tools/>
#
# SPDX-License-Identifier: EPL-2.0

set -eu
script_dir=$(cd -- "$(dirname -- "$0")" > /dev/null && pwd)
node_bin="${script_dir}/.node/bin"
export PATH="${node_bin}:${PATH}"
exec "${node_bin}/yarn" "$@"
