/*
 * generated by Xtext 2.25.0
 */
package tools.refinery.language.web;

import org.eclipse.xtext.util.DisposableRegistry;

import jakarta.servlet.ServletException;
import tools.refinery.language.web.xtext.XtextServlet;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
public class ProblemServlet extends XtextServlet {

	private static final long serialVersionUID = -9204695886561362912L;

	private transient DisposableRegistry disposableRegistry;

	@Override
	public void init() throws ServletException {
		super.init();
		var injector = new ProblemWebSetup().createInjectorAndDoEMFRegistration();
		this.disposableRegistry = injector.getInstance(DisposableRegistry.class);
	}

	@Override
	public void destroy() {
		if (disposableRegistry != null) {
			disposableRegistry.dispose();
			disposableRegistry = null;
		}
		super.destroy();
	}

}
