/*
 * generated by Xtext 2.25.0
 */
package tools.refinery.language.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ProblemWebModule extends AbstractProblemWebModule {
}
