<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="problem" nsURI="https://refinery.tools/emf/2021/Problem" nsPrefix="problem">
  <eClassifiers xsi:type="ecore:EClass" name="Problem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ModuleKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//Statement #//Relation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureDeclarations" upperBound="-1"
        eType="#//FeatureDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newNode" eType="#//Node"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceDeclaration" eSuperTypes="#//FeatureDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//ReferenceDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ReferenceKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceType" eType="#//Relation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invalidMultiplicity" eType="#//Relation"
        transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredicateDefinition" eSuperTypes="#//ParametricDefinition #//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodies" upperBound="-1"
        eType="#//Conjunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" eType="#//Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//VariableOrNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitiveClosure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" eType="#//Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExistentialQuantifier" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitVariables" upperBound="-1"
        eType="#//ImplicitVariable" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//AssertionArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" eType="#//Relation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//VariableOrNode"/>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicValue">
    <eLiterals name="TRUE" literal="TRUE"/>
    <eLiterals name="FALSE" value="1"/>
    <eLiterals name="UNKNOWN" value="2"/>
    <eLiterals name="ERROR" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeScopes" upperBound="-1"
        eType="#//TypeScope" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeScope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="increment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetType" eType="#//Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RangeMultiplicity" eSuperTypes="#//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExactMultiplicity" eSuperTypes="#//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exactValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnboundedMultiplicity" eSuperTypes="#//Multiplicity"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDeclaration" eSuperTypes="#//Statement #//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableOrNode" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true" eSuperTypes="#//Expr"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeAssertionArgument" eSuperTypes="#//AssertionArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssertionArgument" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//NodeKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WildcardAssertionArgument" eSuperTypes="#//AssertionArgument"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParametricDefinition" abstract="true"
      interface="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleDefinition" eSuperTypes="#//ParametricDefinition #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consequents" upperBound="-1"
        eType="#//Consequent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preconditions" upperBound="-1"
        eType="#//Conjunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consequent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssertionAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atom" eType="#//Atom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//LogicValue"
        defaultValueLiteral="TRUE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overwrite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="FALSE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableOrNode" eType="#//VariableOrNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//NewVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//VariableOrNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Modality">
    <eLiterals name="DEFAULT" value="1"/>
    <eLiterals name="MAY" value="2"/>
    <eLiterals name="MUST" value="3"/>
    <eLiterals name="CURRENT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOp">
    <eLiterals name="LESS"/>
    <eLiterals name="LESS_EQ" value="1"/>
    <eLiterals name="GREATER" value="2"/>
    <eLiterals name="GREATER_EQ" value="3"/>
    <eLiterals name="EQ" value="4"/>
    <eLiterals name="NOT_EQ" value="5"/>
    <eLiterals name="IN" value="6"/>
    <eLiterals name="SUBSUMES" value="7"/>
    <eLiterals name="SUBSUMED_BY" value="8"/>
    <eLiterals name="ABS_EQ" value="9"/>
    <eLiterals name="ABS_NOT_EQ" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReferenceKind">
    <eLiterals name="REFERENCE" value="1"/>
    <eLiterals name="CONTAINMENT" value="2"/>
    <eLiterals name="CONTAINER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableOrNodeExpr" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableOrNode" eType="#//VariableOrNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singletonVariable" eType="#//ImplicitVariable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpr" abstract="true" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpr" abstract="true" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOp">
    <eLiterals name="PLUS"/>
    <eLiterals name="MINUS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOp">
    <eLiterals name="ADD"/>
    <eLiterals name="SUB" value="1"/>
    <eLiterals name="MUL" value="2"/>
    <eLiterals name="DIV" value="3"/>
    <eLiterals name="POW" value="4"/>
    <eLiterals name="MEET" value="5"/>
    <eLiterals name="JOIN" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticUnaryExpr" eSuperTypes="#//UnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//UnaryOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationExpr" eSuperTypes="#//Expr #//ExistentialQuantifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//AggregationOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationOp">
    <eLiterals name="SUM"/>
    <eLiterals name="PROD" value="1"/>
    <eLiterals name="MIN" value="2"/>
    <eLiterals name="MAX" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpr" eSuperTypes="#//BinaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//ComparisonOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifiedUnaryExpr" abstract="true"
      eSuperTypes="#//ExistentialQuantifier #//UnaryExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDefinition" eSuperTypes="#//ParametricDefinition #//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//Case" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionType" eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Case" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//Case #//ExistentialQuantifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match" eSuperTypes="#//Case">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Conjunction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticBinaryExpr" eSuperTypes="#//BinaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//BinaryOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegationExpr" eSuperTypes="#//QuantifiedUnaryExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="CountExpr" eSuperTypes="#//QuantifiedUnaryExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModalExpr" eSuperTypes="#//UnaryExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modality" eType="#//Modality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeExpr" eSuperTypes="#//BinaryExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfConstant" eSuperTypes="#//Constant"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureDeclaration" abstract="true"
      eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDeclaration" eSuperTypes="#//FeatureDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeType" eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlagDeclaration" eSuperTypes="#//FeatureDeclaration"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="INT"/>
    <eLiterals name="REAL" value="1"/>
    <eLiterals name="STRING" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logicValue" eType="#//LogicValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModuleKind">
    <eLiterals name="PROBLEM"/>
    <eLiterals name="MODULE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NodeKind">
    <eLiterals name="NODE"/>
    <eLiterals name="ATOM" value="1"/>
    <eLiterals name="MULTI" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedModule" eType="#//Problem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
