import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
  learnSidebar: [
    {
      type: 'autogenerated',
      dirName: 'learn',
    },
  ],
  developSidebar: [
    {
      type: 'autogenerated',
      dirName: 'develop',
    },
  ],
} satisfies SidebarsConfig;
