/*
 * Copyright (c) 2024 The Refinery Authors <https://refinery.tools/>
 *
 * SPDX-License-Identifier: EPL-2.0
 */

import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
  learnSidebar: [
    {
      type: 'autogenerated',
      dirName: 'learn',
    },
  ],
  developSidebar: [
    {
      type: 'autogenerated',
      dirName: 'develop',
    },
  ],
} satisfies SidebarsConfig;
