/*
 * SPDX-FileCopyrightText: 2021-2023 The Refinery Authors <https://refinery.tools/>
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/*
 * generated by Xtext 2.29.0.M2
 */
package tools.refinery.language.ide.contentassist.antlr;

import org.antlr.runtime.TokenSource;

/**
 * Duplicates the logic from {@link tools.refinery.language.parser.antlr.ProblemTokenSource} to satisfy the Xtext
 * generator.
 * <p>
 * Naming this class <code>ProblemTokenSource</code> is required by Xtext, so we have to silence the naming warning.
 */
@SuppressWarnings("squid:S2176")
public class ProblemTokenSource extends tools.refinery.language.parser.antlr.ProblemTokenSource {
	public ProblemTokenSource(TokenSource delegate) {
		super(delegate);
	}
}
