# SPDX-FileCopyrightText: 2024-2026 The Refinery Authors <https://refinery.tools/>
#
# SPDX-License-Identifier: EPL-2.0

FROM base AS cli
ARG TARGETARCH
ADD --link extracted/cli_lib /app/lib
ADD --link extracted/cli_app_lib /app/lib
ADD --link extracted/cli_${TARGETARCH}_bin /app/bin
ENV REFINERY_LIBRARY_PATH=/data
USER 1000
WORKDIR /data
ENTRYPOINT ["/app/bin/refinery-generator-cli"]
