/*
 * SPDX-FileCopyrightText: 2021-2023 The Refinery Authors <https://refinery.tools/>
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/*
 * generated by Xtext 2.25.0
 */
package tools.refinery.language.web;

import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

import tools.refinery.language.ProblemRuntimeModule;
import tools.refinery.language.ProblemStandaloneSetup;
import tools.refinery.language.ide.ProblemIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class ProblemWebSetup extends ProblemStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ProblemRuntimeModule(), new ProblemIdeModule(), new ProblemWebModule()));
	}
	
}
